version: "3.7"
services:
  mysqldb:
    build: ./dbService
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE 
    ports:
      - $MYSQLDB_EXPOSE_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - databaseyapechallenge:/var/lib/mysql
    networks:
      - yape_challenge
      
  transaction_ms:
    build: ./transactionMicroService
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - PORT_TRANSACTION_MICROSERVICE=$PORT_DOCKER_TRANSACTION_MICROSERVICE
      - KAFKA_TOPIC=$KAFKA_TOPIC
      - KAFKA_TOPIC_REPLY=$KAFKA_TOPIC_REPLY
      - KAFKA_CONSUMER_ID=$KAFKA_CONSUMER_ID
      - KAFKA_URL=kafka:9092
    ports:
      - ${PORT_EXPORT_TRANSACTION_MICROSERVICE}:$PORT_DOCKER_TRANSACTION_MICROSERVICE
    depends_on:
      - mysqldb
      - kafka
    networks:
      - yape_challenge

  antifraud_ms:
    build: ./antiFraudMicroService
    restart: unless-stopped
    environment:
      - PORT_ANTIFRAUD_MICROSERVICE=$PORT_ANTIFRAUD_MICROSERVICE
      - KAFKA_URL=kafka:9092
    depends_on:
      - mysqldb
      - kafka
    networks:
      - yape_challenge
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - yape_challenge
  kafka:
    image: confluentinc/cp-enterprise-kafka:5.5.3
    depends_on: [zookeeper]
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9991
      KAFKA_CREATE_TOPICS: ${KAFKA_TOPIC}:1:1,${KAFKA_TOPIC_REPLY}:1:1
    ports:
      - 9092:9092
      - 29092:29092
    networks:
      - yape_challenge

volumes:
  databaseyapechallenge:

networks:
  yape_challenge:
    driver: bridge