export const CREATE_TRANSACTION_TABLE = `CREATE TABLE TRANSACTION_INFO (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ACCOUNT_DEBIT_ID VARCHAR(50),
  ACCOUNT_CREDIT_ID VARCHAR(50),
  STATUS VARCHAR(10),
  TRANSFER_TYPE INT,
  REGISTER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP)
`;
export const CREATE_TRANSACTION = `
  INSERT INTO TRANSACTION_INFO ( ACCOUNT_DEBIT_ID, ACCOUNT_CREDIT_ID, STATUS, TRANSFER_TYPE )
  VALUES ( :accountDebitId, :accountCreditId, :statusTransaction, :transferType )`;

export const UPDATE_TRANSACTION_STATUS = `
  UPDATE TRANSACTION_INFO
  SET STATUS = :statusTransaction
  WHERE ACCOUNT_DEBIT_ID = :accountDebitId 
  AND ACCOUNT_CREDIT_ID = :accountCreditId `