export const CREATE_TRANSACTION_TABLE = `CREATE TABLE TRANSACTION_INFO (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ACCOUNT_DEBIT_ID VARCHAR(50),
  ACCOUNT_CREDIT_ID VARCHAR(50),
  EXTERNAL_ID VARCHAR(50),
  VALUE_TRANSACTION INT,
  STATUS VARCHAR(10),
  TRANSFER_TYPE INT,
  REGISTER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP)
`;
export const CREATE_TRANSACTION = `
  INSERT INTO TRANSACTION_INFO ( ACCOUNT_DEBIT_ID, ACCOUNT_CREDIT_ID, STATUS, TRANSFER_TYPE, EXTERNAL_ID, VALUE_TRANSACTION )
  VALUES ( :accountDebitId, :accountCreditId, :statusTransaction, :transferType, :externalId, :value )`;

export const UPDATE_TRANSACTION_STATUS = `
  UPDATE TRANSACTION_INFO
  SET STATUS = :statusTransaction
  WHERE EXTERNAL_ID = :externalId`;

export const GET_INFO_TRANSACTION = `
SELECT 
ACCOUNT_DEBIT_ID as 'accountDebitId',
ACCOUNT_CREDIT_ID as 'accountCreditId',
EXTERNAL_ID as 'externalId',
VALUE_TRANSACTION as 'valueTransaction',
STATUS as 'statusTransaction',
TRANSFER_TYPE as 'transferType',
REGISTER_DATE as 'createdAt'
FROM TRANSACTION_INFO
WHERE EXTERNAL_ID = :externalIdValue`;