CREATE TABLE IF NOT EXISTS TRANSACTION_INFO (
ID INT AUTO_INCREMENT PRIMARY KEY,
ACCOUNT_DEBIT_ID VARCHAR(50),
ACCOUNT_CREDIT_ID VARCHAR(50),
EXTERNAL_ID VARCHAR(50),
VALUE_TRANSACTION INT,
STATUS VARCHAR(10),
TRANSFER_TYPE INT,
REGISTER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP);